### ISSUE TITLE
Model Timestamp

### ISSUE THREAD

**Issue by frauzufall** [bioimage-io/configuration#45]
Should the model also get a timestamp, not just the weights?

**Comment by oeway** [comment]
Could you elaborate the use case for the timestamp of a model? You mean the time when the model architecture is developed?

**Comment by frauzufall** [comment]
No, the timestamp when the model specification was created. Just as additional information, similar to the timestamp of the weights. Or does the weights timestamp has a more concrete use case?

**Comment by oeway** [comment]
The timestamp was proposed to sort models when we have multiple models (e.g. snapshots) in the same file and we want to use the time stamp to sort them. With the new config format, the timestamp becomes a bit obsolete.

Since the weights are the same set of numbers in different formats, it might make more sense to take the timestamp key out of the weights and add to the models. And we can define it as when the training was done (which might be more important than when the spec was created?). Having a timestamp for each format, which would mean when did we convert the model format, is not very useful.

What do you think?

@constantinpape @FynnBe

**Comment by constantinpape** [comment]
I agree, the timestamp is not really necessary any more, we can remove it to simplify the weight definition.

**Comment by FynnBe** [comment]
I like @oeway idea of adding it to root as the training time (It doesn't realy matter when weights were converted to a different format). We still can use it for sorting when grouping models (independent of how exactly we group).

**Comment by constantinpape** [comment]
This was fixed by #47.
